# Generated by Django 5.1.2 on 2024-12-13 23:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_alter_leaverequest_manager_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to='workspace.userprofile'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='type',
            field=models.CharField(blank=True, choices=[('WFH', 'Work from Home'), ('IO', 'In Office'), ('AL', 'Annual Leave'), ('S', 'Sick'), ('FL', 'Flexi Leave'), ('NWD', 'Non Working Day'), ('BT', 'Business Travel'), ('T', 'Training')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('SL', 'Sick Leave'), ('PL', 'Personal Leave'), ('AL', 'Annual Leave'), ('FL', 'Flexi Leave'), ('NWD', 'Non Working Day')], max_length=3),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_to_approve', to='workspace.userprofile'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Cancellation Pending', 'Cancellation Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
