# Generated by Django 5.1.2 on 2024-12-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_leaverequest_created_at_userprofile_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
