name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual runs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          cd multi_tracker  # Navigate to the directory
          python manage.py migrate

      - name: Run tests
        run: |
          cd multi_tracker  # Navigate to the directory
          python manage.py test

      - name: Debug Email Configuration
        run: |
          echo "Testing EMAIL: $EMAIL_HOST_USER"
