name: Django CI/CD

on:
  push:
    branches:
      - '**'  # Run Actions on all branches
  pull_request:
    branches:
      - main  # Still check PRs targeting main
  workflow_dispatch:  # Allows manual runs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r multi_tracker/requirements.txt

      - name: Install Node.js and Tailwind CLI
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node dependencies
        run: |
          cd multi_tracker
          npm install  # Ensure you have package.json in your repo

      - name: Build Tailwind CSS
        run: |
          cd multi_tracker
          npx tailwindcss -i workspace/static/css/tailwind.css -o workspace/static/css/output.css --minify

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> $GITHUB_ENV
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> $GITHUB_ENV

      - name: Run migrations
        run: |
          cd multi_tracker
          python manage.py migrate

      - name: Collect static files
        run: |
          cd multi_tracker
          python manage.py collectstatic --noinput

      - name: Run tests
        run: |
          cd multi_tracker
          python manage.py test

      - name: Debug Email Configuration
        run: |
          echo "Testing EMAIL: $EMAIL_HOST_USER"
